title: Document Analysis Semester Project
description: This repository contains the report for our group project for the course Document Analysis, as well as the code to replicate our findings.
show_downloads: True
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - REPORT.md

theme: jekyll-theme-minimal
